INSERT INTO "public"."filiale" ("nome", "città", "tipo", "indirizzo") VALUES 
('Capital Knot', 'Central Region', 'Magazzino', '122 Bridge Road'), 
('Craftsman Loc', 'Mountain Region', 'Punto di Controllo', '103 Artisan Dr '), 
('Distributor NW', 'Central Region', 'Punto di Controllo', '34 NW Access '),
 ('Doctor Loc', 'Mountain Region', 'Punto di Controllo', '89 Medical Dr '), 
 ('Elder', 'Central Region', 'Locker', '42 Veteran Ave '), 
 ('Engineer Loc', 'East Region', 'Punto di Controllo', '57 Tech Street '), 
 ('Film Direct', 'Central Region', 'Locker', '76 Cinema Way '), 
 ('Geologist Loc', 'Mountain Region', 'Locker', '125 Mineral St'), 
 ('Lake Knot', 'Central Region', 'Magazzino', '47 Lake Avenue '), 
 ('Mountain Knot', 'Mountain Region', 'Magazzino', '62 Peak Road '), 
 ('Port Knot', 'East Region', 'Magazzino', '155 Harbor Way '), 
 ('South Knot', 'Central Region', 'Punto di Controllo', '83 Southern St '), 
 ('Timefall', 'East Region', 'Locker', '29 Rain Drive '), 
 ('Weather Stat', 'East Region', 'Locker', '91 Forecast St '), 
 ('WindFarm', 'Central Region', 'Locker', '18 Turbine Path');